name: First Workflow

on:
  push:


jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm install
      working-directory: ./nodejs-shopping

    - name: Run app or tests
      run: npm start
      working-directory: ./nodejs-shopping
