name: First23

on:
  push:


jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Print message
      run: echo "My first CI/CD"

    - name: Running unit test cases
      run: npm start
